on: push

jobs:
  RunTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Don't run when merging.
    if: ${{ !github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        id: run_script
        run: |
          output=$(./answer-to-universe.sh)
          echo "answer_to_universe=$output" >> "$GITHUB_OUTPUT"
      - name: Verify script output
        run: |
          if [ ${{ steps.run_script.answer_to_universe }} -eq 42 ]; then
            echo "The script returned 42, as expected."
          else
            echo "Script returned: ${{ steps.run_script.answer_to_universe }}"
            exit 1
          fi
