on: push

jobs:
  defaults:
    shell: bash

  RunTest:
    # Don't run when merging.
    if: ${{ !github.event.pull_request.merged }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run test script
      id: run_script
      run: |
        output=$(./answer-to-universe.sh)
        echo "answer_to_universe=$output" >> "$GITHUB_OUTPUT"

    - name: Verify script output
      run: |
        if [ ${{ steps.run_script.answer_to_universe }} -eq 42 ]; then
          echo "The script returned 42, as expected."
        else
          echo "Script returned: ${{ steps.run_script.answer_to_universe }}"
          exit 1
        fi
